package com.jmod.core.common.material;

public enum MaterialProperties {
    HAS_FLUID_PIPE, HAS_ITEM_PIPE, HAS_WIRE_AND_CABLE,
    IS_MAGNETIC, IS_MOLTEN, IS_FLUID, IS_GAS, IS_PLASMA,
    HAS_INGOT, HAS_DUST, HAS_ORE, HAS_GEM, HAS_ROD, HAS_PLATE,
    HAS_GEAR, HAS_ROTOR, HAS_SPRING, HAS_CASING, HAS_FRAME, HAS_BLOCK,
    HAS_LENS, HAS_FLUID_CELL, HAS_TANK_WALL, HAS_FOIL, HAS_FINE_WIRE,
    HAS_RING, HAS_SCREW, HAS_HOT,
    CAN_COMPRESS,
    HAS_TOOL_HEADS, HAS_EXPANDED_TOOLS, HAS_TOOLS, HAS_ARMOR, HAS_ARMOR_PARTS, HAS_ELECTRIC_TOOLS_AND_TOOL_HEADS,
    IS_ENCHANTMENT_UPGRADE, IS_CHEST, IS_DRUM
}
